In [1]:
#第13章/定义字典
vocab_x = '<SOS>,<EOS>,<PAD>,0,1,2,3,4,5,6,7,8,9,q,w,e,r,t,y,u,i,o,p,a,s,d,f,g,h,j,k,l,z,x,c,v,b,n,m'
vocab_x = {word: i for i, word in enumerate(vocab_x.split(','))}

vocab_xr = [k for k, v in vocab_x.items()]

vocab_y = {k.upper(): v for k, v in vocab_x.items()}

vocab_yr = [k for k, v in vocab_y.items()]

print('vocab_x=', vocab_x)
print('vocab_y=', vocab_y)

vocab_x= {'<SOS>': 0, '<EOS>': 1, '<PAD>': 2, '0': 3, '1': 4, '2': 5, '3': 6, '4': 7, '5': 8, '6': 9, '7': 10, '8': 11, '9': 12, 'q': 13, 'w': 14, 'e': 15, 'r': 16, 't': 17, 'y': 18, 'u': 19, 'i': 20, 'o': 21, 'p': 22, 'a': 23, 's': 24, 'd': 25, 'f': 26, 'g': 27, 'h': 28, 'j': 29, 'k': 30, 'l': 31, 'z': 32, 'x': 33, 'c': 34, 'v': 35, 'b': 36, 'n': 37, 'm': 38}
vocab_y= {'<SOS>': 0, '<EOS>': 1, '<PAD>': 2, '0': 3, '1': 4, '2': 5, '3': 6, '4': 7, '5': 8, '6': 9, '7': 10, '8': 11, '9': 12, 'Q': 13, 'W': 14, 'E': 15, 'R': 16, 'T': 17, 'Y': 18, 'U': 19, 'I': 20, 'O': 21, 'P': 22, 'A': 23, 'S': 24, 'D': 25, 'F': 26, 'G': 27, 'H': 28, 'J': 29, 'K': 30, 'L': 31, 'Z': 32, 'X': 33, 'C': 34, 'V': 35, 'B': 36, 'N': 37, 'M': 38}


In [2]:
#第13章/定义生成数据函数
import random

import numpy as np
import torch


def get_data():
    #定义词集合
    words = [
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'q', 'w', 'e', 'r',
        't', 'y', 'u', 'i', 'o', 'p', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k',
        'l', 'z', 'x', 'c', 'v', 'b', 'n', 'm'
    ]

    #定义每个词被选中的概率
    p = np.array([
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
        13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26
    ])
    p = p / p.sum()

    #随机选n个词
    n = random.randint(30, 48)
    x = np.random.choice(words, size=n, replace=True, p=p)

    #采样的结果就是x
    x = x.tolist()

    #y是对x的变换得到的
    #字母大写,数字取9以内的互补数
    def f(i):
        i = i.upper()
        if not i.isdigit():
            return i
        i = 9 - int(i)
        return str(i)

    y = [f(i) for i in x]
    #逆序
    y = y[::-1]

    #y中的首字母双写
    y = [y[0]] + y

    #加上首尾符号
    x = ['<SOS>'] + x + ['<EOS>']
    y = ['<SOS>'] + y + ['<EOS>']

    #补pad到固定长度
    x = x + ['<PAD>'] * 50
    y = y + ['<PAD>'] * 51
    x = x[:50]
    y = y[:51]

    #编码成数据
    x = [vocab_x[i] for i in x]
    y = [vocab_y[i] for i in y]

    #转tensor
    x = torch.LongTensor(x)
    y = torch.LongTensor(y)

    return x, y


get_data()

(tensor([ 0, 20, 38, 18, 23, 35, 38, 19, 33, 33, 25, 34, 34, 32, 27, 19, 32, 20,
         38, 38, 36, 38, 26, 28, 33, 34, 33, 38,  5, 16, 30, 30, 35, 33, 25, 22,
         38, 21, 35, 29, 26, 10, 33, 34, 11, 12, 32,  1,  2,  2]),
 tensor([ 0, 32, 32,  3,  4, 34, 33,  5, 26, 29, 35, 21, 38, 22, 25, 33, 35, 30,
         30, 16, 10, 38, 33, 34, 33, 28, 26, 38, 36, 38, 38, 20, 32, 19, 27, 32,
         34, 34, 25, 33, 33, 19, 38, 35, 23, 18, 38, 20,  1,  2,  2]))

In [3]:
#第13章/两数相加测试
#使用这份数据请把训练次数改为10
def get_data():
    #定义词集合
    words = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

    #定义每个词被选中的概率
    p = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    p = p / p.sum()

    #随机选n个词
    n = random.randint(10, 20)
    s1 = np.random.choice(words, size=n, replace=True, p=p)

    #采样的结果就是s1
    s1 = s1.tolist()

    #同样的方法,再采出s2
    n = random.randint(10, 20)
    s2 = np.random.choice(words, size=n, replace=True, p=p)
    s2 = s2.tolist()

    #y等于s1和s2数值上的相加
    y = int(''.join(s1)) + int(''.join(s2))
    y = list(str(y))

    #x等于s1和s2字符上的相加
    x = s1 + ['a'] + s2

    #加上首尾符号
    x = ['<SOS>'] + x + ['<EOS>']
    y = ['<SOS>'] + y + ['<EOS>']

    #补pad到固定长度
    x = x + ['<PAD>'] * 50
    y = y + ['<PAD>'] * 51
    x = x[:50]
    y = y[:51]

    #编码成数据
    x = [vocab_x[i] for i in x]
    y = [vocab_y[i] for i in y]

    #转tensor
    x = torch.LongTensor(x)
    y = torch.LongTensor(y)

    return x, y


get_data()

(tensor([ 0,  7,  7, 11,  9,  8,  9,  8, 11,  4,  5, 11, 10, 11, 10,  9, 23,  8,
          7,  6, 12,  5,  8,  8,  4,  3,  8, 11,  1,  2,  2,  2,  2,  2,  2,  2,
          2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2]),
 tensor([ 0,  7,  7, 11, 10,  4,  3, 12, 10,  6, 11,  6, 11, 12,  6,  7,  1,  2,
          2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
          2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2]))

In [4]:
#第13章/定义数据集和加载器
#定义数据集
class Dataset(torch.utils.data.Dataset):
    def __init__(self):
        super(Dataset, self).__init__()

    def __len__(self):
        return 100000

    def __getitem__(self, i):
        return get_data()


#数据加载器
loader = torch.utils.data.DataLoader(dataset=Dataset(),
                                     batch_size=8,
                                     drop_last=True,
                                     shuffle=True,
                                     collate_fn=None)

#查看数据样例
for i, (x, y) in enumerate(loader):
    break

x.shape, y.shape

(torch.Size([8, 50]), torch.Size([8, 51]))

In [5]:
#第13章/定义mask_pad函数
def mask_pad(data):
    #b句话,每句话50个词,这里是还没embed的
    #data = [b, 50]
    #判断每个词是不是<PAD>
    mask = data == vocab_x['<PAD>']

    #[b, 50] -> [b, 1, 1, 50]
    mask = mask.reshape(-1, 1, 1, 50)

    #在计算注意力时,是计算50个词和50个词相互之间的注意力,所以是个50*50的矩阵
    #是pad的列是true,意味着任何词对pad的注意力都是0
    #但是pad本身对其他词的注意力并不是0
    #所以是pad的行不是true

    #复制n次
    #[b, 1, 1, 50] -> [b, 1, 50, 50]
    mask = mask.expand(-1, 1, 50, 50)

    return mask


mask_pad(x[:1])

tensor([[[[False, False, False,  ...,  True,  True,  True],
          [False, False, False,  ...,  True,  True,  True],
          [False, False, False,  ...,  True,  True,  True],
          ...,
          [False, False, False,  ...,  True,  True,  True],
          [False, False, False,  ...,  True,  True,  True],
          [False, False, False,  ...,  True,  True,  True]]]])

In [6]:
#第13章/定义mask_tril函数
def mask_tril(data):
    #b句话,每句话50个词,这里是还没embed的
    #data = [b, 50]

    #50*50的矩阵表示每个词对其他词是否可见
    #上三角矩阵,不包括对角线,意味着,对每个词而言,他只能看到他自己,和他之前的词,而看不到之后的词
    #[1, 50, 50]
    """
    [[0, 1, 1, 1, 1],
     [0, 0, 1, 1, 1],
     [0, 0, 0, 1, 1],
     [0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0]]"""
    tril = 1 - torch.tril(torch.ones(1, 50, 50, dtype=torch.long))

    #判断y当中每个词是不是pad,如果是pad则不可见
    #[b, 50]
    mask = data == vocab_y['<PAD>']

    #变形+转型,为了之后的计算
    #[b, 1, 50]
    mask = mask.unsqueeze(1).long()

    #mask和tril求并集
    #[b, 1, 50] + [1, 50, 50] -> [b, 50, 50]
    mask = mask + tril

    #转布尔型
    mask = mask > 0

    #转布尔型,增加一个维度,便于后续的计算
    mask = (mask == 1).unsqueeze(dim=1)

    return mask

mask_tril(x[:1])

tensor([[[[False,  True,  True,  ...,  True,  True,  True],
          [False, False,  True,  ...,  True,  True,  True],
          [False, False, False,  ...,  True,  True,  True],
          ...,
          [False, False, False,  ...,  True,  True,  True],
          [False, False, False,  ...,  True,  True,  True],
          [False, False, False,  ...,  True,  True,  True]]]])

In [7]:
#第13章/定义注意力计算函数
def attention(Q, K, V, mask):
    #b句话,每句话50个词,每个词编码成32维向量,4个头,每个头分到8维向量
    #Q、K、V = [b, 4, 50, 8]

    #[b, 4, 50, 8] * [b, 4, 8, 50] -> [b, 4, 50, 50]
    #Q、K矩阵相乘,求每个词相对其他所有词的注意力
    score = torch.matmul(Q, K.permute(0, 1, 3, 2))

    #除以每个头维数的平方根,做数值缩放
    score /= 8**0.5

    #mask遮盖,mask是true的地方都被替换成-inf,这样在计算softmax的时候,-inf会被压缩到0
    #mask = [b, 1, 50, 50]
    score = score.masked_fill_(mask, -float('inf'))
    score = torch.softmax(score, dim=-1)

    #以注意力分数乘以V,得到最终的注意力结果
    #[b, 4, 50, 50] * [b, 4, 50, 8] -> [b, 4, 50, 8]
    score = torch.matmul(score, V)

    #每个头计算的结果合一
    #[b, 4, 50, 8] -> [b, 50, 32]
    score = score.permute(0, 2, 1, 3).reshape(-1, 50, 32)

    return score


attention(torch.randn(8, 4, 50, 8), torch.randn(8, 4, 50, 8),
          torch.randn(8, 4, 50, 8), torch.zeros(8, 1, 50, 50)).shape

torch.Size([8, 50, 32])

In [8]:
#第13章/BatchNorm1d和LayerNorm的对比
#标准化之后,均值是0,标准差是1
#BN是取不同样本做标准化
#LN是取不同通道做标准化
#affine=True,elementwise_affine=True,指定标准化后,再计算一个线性映射
norm = torch.nn.BatchNorm1d(num_features=4, affine=True)
print(norm(torch.arange(32, dtype=torch.float32).reshape(2, 4, 4)))

norm = torch.nn.LayerNorm(normalized_shape=4, elementwise_affine=True)
print(norm(torch.arange(32, dtype=torch.float32).reshape(2, 4, 4)))

tensor([[[-1.1761, -1.0523, -0.9285, -0.8047],
         [-1.1761, -1.0523, -0.9285, -0.8047],
         [-1.1761, -1.0523, -0.9285, -0.8047],
         [-1.1761, -1.0523, -0.9285, -0.8047]],

        [[ 0.8047,  0.9285,  1.0523,  1.1761],
         [ 0.8047,  0.9285,  1.0523,  1.1761],
         [ 0.8047,  0.9285,  1.0523,  1.1761],
         [ 0.8047,  0.9285,  1.0523,  1.1761]]],
       grad_fn=<NativeBatchNormBackward0>)
tensor([[[-1.3416, -0.4472,  0.4472,  1.3416],
         [-1.3416, -0.4472,  0.4472,  1.3416],
         [-1.3416, -0.4472,  0.4472,  1.3416],
         [-1.3416, -0.4472,  0.4472,  1.3416]],

        [[-1.3416, -0.4472,  0.4472,  1.3416],
         [-1.3416, -0.4472,  0.4472,  1.3416],
         [-1.3416, -0.4472,  0.4472,  1.3416],
         [-1.3416, -0.4472,  0.4472,  1.3416]]],
       grad_fn=<NativeLayerNormBackward0>)


In [9]:
#第13章/多头注意力计算层
class MultiHead(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.fc_Q = torch.nn.Linear(32, 32)
        self.fc_K = torch.nn.Linear(32, 32)
        self.fc_V = torch.nn.Linear(32, 32)

        self.out_fc = torch.nn.Linear(32, 32)

        self.norm = torch.nn.LayerNorm(normalized_shape=32,
                                       elementwise_affine=True)

        self.dropout = torch.nn.Dropout(p=0.1)

    def forward(self, Q, K, V, mask):
        #b句话,每句话50个词,每个词编码成32维向量
        #Q、K、V = [b, 50, 32]
        b = Q.shape[0]

        #保留下原始的Q,后面要做短接用
        clone_Q = Q.clone()

        #标准化
        Q = self.norm(Q)
        K = self.norm(K)
        V = self.norm(V)

        #线性运算,维度不变
        #[b, 50, 32] -> [b, 50, 32]
        K = self.fc_K(K)
        V = self.fc_V(V)
        Q = self.fc_Q(Q)

        #拆分成多个头
        #b句话,每句话50个词,每个词编码成32维向量,4个头,每个头分到8维向量
        #[b, 50, 32] -> [b, 4, 50, 8]
        Q = Q.reshape(b, 50, 4, 8).permute(0, 2, 1, 3)
        K = K.reshape(b, 50, 4, 8).permute(0, 2, 1, 3)
        V = V.reshape(b, 50, 4, 8).permute(0, 2, 1, 3)

        #计算注意力
        #[b, 4, 50, 8] -> [b, 50, 32]
        score = attention(Q, K, V, mask)

        #计算输出,维度不变
        #[b, 50, 32] -> [b, 50, 32]
        score = self.dropout(self.out_fc(score))

        #短接
        score = clone_Q + score
        return score


MultiHead()(torch.randn(8, 50, 32), torch.randn(8, 50, 32),
            torch.randn(8, 50, 32), torch.zeros(8, 1, 50, 50)).shape

torch.Size([8, 50, 32])

In [10]:
#第13章/定义位置编码层
import math


class PositionEmbedding(torch.nn.Module):
    def __init__(self):
        super().__init__()

        #pos是第几个词,i是第几个维度,d_model是维度总数
        def get_pe(pos, i, d_model):
            d = 1e4**(i / d_model)
            pe = pos / d

            if i % 2 == 0:
                return math.sin(pe)
            return math.cos(pe)

        #初始化位置编码矩阵
        pe = torch.empty(50, 32)
        for i in range(50):
            for j in range(32):
                pe[i, j] = get_pe(i, j, 32)
        pe = pe.unsqueeze(0)

        #定义为不更新的常量
        self.register_buffer('pe', pe)

        #词编码层
        self.embed = torch.nn.Embedding(39, 32)
        #初始化参数
        self.embed.weight.data.normal_(0, 0.1)

    def forward(self, x):
        #[8, 50] -> [8, 50, 32]
        embed = self.embed(x)

        #词编码和位置编码相加
        #[8, 50, 32] + [1, 50, 32] -> [8, 50, 32]
        embed = embed + self.pe
        return embed


PositionEmbedding()(torch.ones(8, 50).long()).shape

torch.Size([8, 50, 32])

In [11]:
#第13章/定义全连接输出层
class FullyConnectedOutput(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = torch.nn.Sequential(
            torch.nn.Linear(in_features=32, out_features=64),
            torch.nn.ReLU(),
            torch.nn.Linear(in_features=64, out_features=32),
            torch.nn.Dropout(p=0.1),
        )

        self.norm = torch.nn.LayerNorm(normalized_shape=32,
                                       elementwise_affine=True)

    def forward(self, x):
        #保留下原始的x,后面要做短接用
        clone_x = x.clone()

        #标准化
        x = self.norm(x)

        #线性全连接运算
        #[b, 50, 32] -> [b, 50, 32]
        out = self.fc(x)

        #做短接
        out = clone_x + out

        return out


FullyConnectedOutput()(torch.randn(8, 50, 32)).shape

torch.Size([8, 50, 32])

In [12]:
#第13章/定义编码器
#编码器层
class EncoderLayer(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.mh = MultiHead()
        self.fc = FullyConnectedOutput()

    def forward(self, x, mask):
        #计算自注意力,维度不变
        #[b, 50, 32] -> [b, 50, 32]
        score = self.mh(x, x, x, mask)

        #全连接输出,维度不变
        #[b, 50, 32] -> [b, 50, 32]
        out = self.fc(score)

        return out


#编码器
class Encoder(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_1 = EncoderLayer()
        self.layer_2 = EncoderLayer()
        self.layer_3 = EncoderLayer()

    def forward(self, x, mask):
        x = self.layer_1(x, mask)
        x = self.layer_2(x, mask)
        x = self.layer_3(x, mask)
        return x


Encoder()(torch.randn(8, 50, 32), torch.ones(8, 1, 50, 50)).shape

torch.Size([8, 50, 32])

In [13]:
#第13章/定义解码器
#解码器层
class DecoderLayer(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.mh1 = MultiHead()
        self.mh2 = MultiHead()

        self.fc = FullyConnectedOutput()

    def forward(self, x, y, mask_pad_x, mask_tril_y):
        #先计算y的自注意力,维度不变
        #[b, 50, 32] -> [b, 50, 32]
        y = self.mh1(y, y, y, mask_tril_y)

        #结合x和y的注意力计算,维度不变
        #[b, 50, 32],[b, 50, 32] -> [b, 50, 32]
        y = self.mh2(y, x, x, mask_pad_x)

        #全连接输出,维度不变
        #[b, 50, 32] -> [b, 50, 32]
        y = self.fc(y)

        return y


#解码器
class Decoder(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.layer_1 = DecoderLayer()
        self.layer_2 = DecoderLayer()
        self.layer_3 = DecoderLayer()

    def forward(self, x, y, mask_pad_x, mask_tril_y):
        y = self.layer_1(x, y, mask_pad_x, mask_tril_y)
        y = self.layer_2(x, y, mask_pad_x, mask_tril_y)
        y = self.layer_3(x, y, mask_pad_x, mask_tril_y)
        return y


Decoder()(torch.randn(8, 50, 32), torch.randn(8, 50, 32),
          torch.ones(8, 1, 50, 50), torch.ones(8, 1, 50, 50)).shape

torch.Size([8, 50, 32])

In [14]:
#第13章/定义主模型
class Transformer(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.embed_x = PositionEmbedding()
        self.embed_y = PositionEmbedding()
        self.encoder = Encoder()
        self.decoder = Decoder()
        self.fc_out = torch.nn.Linear(32, 39)

    def forward(self, x, y):
        #[b, 1, 50, 50]
        mask_pad_x = mask_pad(x)
        mask_tril_y = mask_tril(y)

        #编码,添加位置信息
        #x = [b, 50] -> [b, 50, 32]
        #y = [b, 50] -> [b, 50, 32]
        x, y = self.embed_x(x), self.embed_y(y)

        #编码层计算
        #[b, 50, 32] -> [b, 50, 32]
        x = self.encoder(x, mask_pad_x)

        #解码层计算
        #[b, 50, 32],[b, 50, 32] -> [b, 50, 32]
        y = self.decoder(x, y, mask_pad_x, mask_tril_y)

        #全连接输出,维度不变
        #[b, 50, 32] -> [b, 50, 39]
        y = self.fc_out(y)

        return y


model = Transformer()

model(torch.ones(8, 50).long(), torch.ones(8, 50).long()).shape

torch.Size([8, 50, 39])

In [15]:
#第13章/定义预测函数
def predict(x):
    #x = [1, 50]
    model.eval()

    #[1, 1, 50, 50]
    mask_pad_x = mask_pad(x)

    #初始化输出,这个是固定值
    #[1, 50]
    #[[0,2,2,2...]]
    target = [vocab_y['<SOS>']] + [vocab_y['<PAD>']] * 49
    target = torch.LongTensor(target).unsqueeze(0)

    #x编码,添加位置信息
    #[1, 50] -> [1, 50, 32]
    x = model.embed_x(x)

    #编码层计算,维度不变
    #[1, 50, 32] -> [1, 50, 32]
    x = model.encoder(x, mask_pad_x)

    #遍历生成第1个词到第49个词
    for i in range(49):
        #[1, 50]
        y = target

        #[1, 1, 50, 50]
        mask_tril_y = mask_tril(y)

        #y编码,添加位置信息
        #[1, 50] -> [1, 50, 32]
        y = model.embed_y(y)

        #解码层计算,维度不变
        #[1, 50, 32],[1, 50, 32] -> [1, 50, 32]
        y = model.decoder(x, y, mask_pad_x, mask_tril_y)

        #全连接输出,39分类
        #[1, 50, 32] -> [1, 50, 39]
        out = model.fc_out(y)

        #取出当前词的输出
        #[1, 50, 39] -> [1, 39]
        out = out[:, i, :]

        #取出分类结果
        #[1, 39] -> [1]
        out = out.argmax(dim=1).detach()

        #以当前词预测下一个词,填到结果中
        target[:, i + 1] = out

    return target


predict(torch.ones(1, 50).long())

tensor([[ 0, 18, 18, 11, 11,  0,  0,  0,  7,  0, 26,  0,  0,  0, 21, 19, 19, 19,
         19, 19, 19, 21, 21,  0,  0,  0, 21, 21, 21, 21, 19, 19, 19, 21, 21, 21,
         21, 21, 21, 21, 21, 21, 16, 16, 19, 19, 19, 21, 21, 21]])

In [16]:
#第13章/定义训练函数
def train():
    loss_func = torch.nn.CrossEntropyLoss()
    optim = torch.optim.Adam(model.parameters(), lr=2e-3)
    sched = torch.optim.lr_scheduler.StepLR(optim, step_size=3, gamma=0.5)

    for epoch in range(10):
        for i, (x, y) in enumerate(loader):
            #x = [8, 50]
            #y = [8, 51]

            #在训练时,是拿y的每一个字符输入,预测下一个字符,所以不需要最后一个字
            #[8, 50, 39]
            pred = model(x, y[:, :-1])

            #[8, 50, 39] -> [400, 39]
            pred = pred.reshape(-1, 39)

            #[8, 51] -> [400]
            y = y[:, 1:].reshape(-1)

            #忽略pad
            select = y != vocab_y['<PAD>']
            pred = pred[select]
            y = y[select]

            loss = loss_func(pred, y)
            optim.zero_grad()
            loss.backward()
            optim.step()

            if i % 2000 == 0:
                #[select, 39] -> [select]
                pred = pred.argmax(1)
                correct = (pred == y).sum().item()
                accuracy = correct / len(pred)
                lr = optim.param_groups[0]['lr']
                print(epoch, i, lr, loss.item(), accuracy)

        sched.step()


train()

0 0 0.002 4.017234802246094 0.0
0 2000 0.002 2.1498022079467773 0.1347517730496454
0 4000 0.002 2.132599353790283 0.176056338028169
0 6000 0.002 2.1317319869995117 0.20588235294117646
0 8000 0.002 2.0808982849121094 0.20422535211267606
0 10000 0.002 2.078150510787964 0.17687074829931973
0 12000 0.002 1.7938580513000488 0.3333333333333333
1 0 0.002 1.787221908569336 0.3237410071942446
1 2000 0.002 1.8628085851669312 0.25
1 4000 0.002 1.7083605527877808 0.3404255319148936
1 6000 0.002 1.720707893371582 0.3561643835616438
1 8000 0.002 1.3579456806182861 0.47619047619047616
1 10000 0.002 1.0340052843093872 0.5833333333333334
1 12000 0.002 1.405091404914856 0.5771812080536913
2 0 0.002 1.172294020652771 0.6
2 2000 0.002 0.7125112414360046 0.7202797202797203
2 4000 0.002 1.0112520456314087 0.6369426751592356
2 6000 0.002 0.7250597476959229 0.7448275862068966
2 8000 0.002 0.8674978613853455 0.7404580152671756
2 10000 0.002 1.1881616115570068 0.65
2 12000 0.002 0.4675864279270172 0.82666666666

In [17]:
#第13章/测试
def test():
    for i, (x, y) in enumerate(loader):
        break

    for i in range(8):
        print(i)
        print(''.join([vocab_xr[i] for i in x[i].tolist()]))
        print(''.join([vocab_yr[i] for i in y[i].tolist()]))
        print(''.join(
            [vocab_yr[i] for i in predict(x[i].unsqueeze(0))[0].tolist()]))


test()

0
<SOS>69959127972a79068236990629479939<EOS><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>
<SOS>79068237060588607911<EOS><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>
<SOS>79068237060588607911<EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS>117886<EOS><EOS>091287778
1
<SOS>97585554595965a7879935899365<EOS><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>
<SOS>105465490495330<EOS><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>
<SOS>105465490495330<EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS><EOS>2666
2
<SOS>948296474994975a9947925666588821607<EOS><PAD><PAD><PAD><PAD><PAD><PAD